spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store_api
    username: postgres
    password: 100aistuff
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false